/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Order;

import Manage_DMSP.Product;
import static Manage_User.ManageUser.removeDiacriticalMarks;
import Menu.Menu;
import RWFile.RWFileIO;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author nhata
 */
public class ManageOrder extends javax.swing.JFrame {
    double total = 0;
    String filepr = "E:products.txt";
    String fileor = "E:order.txt";
    RWFileIO db = new RWFileIO();
    ArrayList<Order> ltOr = new ArrayList<>();
    //Arrlist temp
    Order link = new Order();
    ArrayList<Product> ltPrT = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel(){
        @Override
            public boolean isCellEditable(int row, int column) {
                // Khóa tất cả các ô
                return false;
            }   
    };
    DefaultTableModel tbmodel = new DefaultTableModel(){
//        @Override
//            public boolean isCellEditable(int row, int column) {
//                // Khóa tất cả các ô
//                return false;
//            }   
    };
    
    public void KhoaChinhSua(){
        txtmadh.setFocusable(false);
        txtMa.setFocusable(false);
        txtTen.setFocusable(false);
        txtSLC.setFocusable(false);
        txtGB.setFocusable(false);
        txttong.setFocusable(false);
    }
    
    public void initTableD() {
        String[] columns = {"Mã sản phẩm", "Tên sản phẩm", "Số lượng có" , "Giá bán", "Số lượng mua"};
        tbmodel.setColumnIdentifiers(columns);
        tbDetail.setModel(tbmodel);
    }
    
    public void HienThiD(ArrayList<Product> ltPr){
        tbmodel.setRowCount(0);        
            for (Product pr : ltPr) {
                Object[] rowData = {pr.getMaSP(), pr.getTenSP(), pr.getSoLuong(), pr.getGiaBan(), pr.getSoLuongMua()};
                tbmodel.addRow(rowData);
            }
    }
    
    public void initTable() {
        String[] columns = {"Mã đơn hàng", "Ngày hoàn thành", "Sản phẩm" , "Tổng tiền"};
        model.setColumnIdentifiers(columns);
        tbDH.setModel(model);
    }
    public void HienThi(ArrayList<Order> ltOr){
        model.setRowCount(0);        
            for (Order o : ltOr) {
                Object[] rowData = {o.getMaDH(), o.getNgayHT(), o.getDsSanPham(), o.getTongTien()};
                model.addRow(rowData);
            }
    }
    public void GetData(){
        try {
                ltOr = (ArrayList<Order>) db.readFile(fileor);//Đưa đối tượng đọc được trong file vào arrayList đã tạo
        } catch (Exception err) {
                JOptionPane.showMessageDialog(this, err.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Creates new form ManageOrder
     */
    public ManageOrder() {
        initComponents();
        GetData();
        initTable();        
        HienThi(ltOr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfDetail = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSLC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGB = new javax.swing.JTextField();
        spslm = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetail = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txttong = new javax.swing.JTextField();
        txtmadh = new javax.swing.JTextField();
        txtngay = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnbk = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDH = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Mã sản phẩm");

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMa.setForeground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Tên sản phẩm");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTen.setForeground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Số lượng có");

        txtSLC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSLC.setForeground(new java.awt.Color(153, 153, 153));
        txtSLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLCActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Giá bán");

        txtGB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGB.setForeground(new java.awt.Color(153, 153, 153));

        spslm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng mua");

        tbDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDetail);

        jLabel9.setText("Tổng tiền");

        txttong.setBackground(new java.awt.Color(255, 255, 153));
        txttong.setForeground(new java.awt.Color(255, 51, 51));
        txttong.setBorder(null);

        txtmadh.setBackground(new java.awt.Color(255, 255, 204));
        txtmadh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmadh.setForeground(new java.awt.Color(255, 51, 51));
        txtmadh.setBorder(null);

        txtngay.setBackground(new java.awt.Color(255, 255, 204));
        txtngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngay.setForeground(new java.awt.Color(255, 51, 51));
        txtngay.setBorder(null);

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfDetailLayout = new javax.swing.GroupLayout(jfDetail.getContentPane());
        jfDetail.getContentPane().setLayout(jfDetailLayout);
        jfDetailLayout.setHorizontalGroup(
            jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfDetailLayout.createSequentialGroup()
                .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jfDetailLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfDetailLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnsua)
                                .addComponent(jLabel6)
                                .addComponent(btnReset))
                            .addComponent(txtmadh, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(46, 46, 46)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(txtTen)
                                .addComponent(txtSLC)
                                .addComponent(txtGB)
                                .addComponent(spslm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtngay))
                            .addGroup(jfDetailLayout.createSequentialGroup()
                                .addComponent(btnxoa)
                                .addGap(54, 54, 54)
                                .addComponent(btnback)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jfDetailLayout.setVerticalGroup(
            jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfDetailLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jfDetailLayout.createSequentialGroup()
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmadh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spslm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsua)
                            .addComponent(btnxoa)
                            .addComponent(btnback)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReset))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");

        btnbk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnbk.setText("Back");
        btnbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbkActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDH);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xóa đơn hàng");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnView.setText("View all");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbk)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiem))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbk)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTimKiem)
                                .addGap(77, 77, 77)))
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(btnXoa)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Order link = new Order();
    private void tbDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDHMouseClicked
        // TODO add your handling code here:
        Order or = new Order();
        int choose = tbDH.getSelectedRow();
        if(choose != -1) {
            or = ltOr.get(choose);
            if(evt.getClickCount() == 2) {
                link = or;
                // Xử lý sự kiện nhấp chuột đúp
                int row = tbDH.rowAtPoint(evt.getPoint());
                // Thực hiện các thao tác mong muốn
                jfDetail.setSize(1100, 600);
                jfDetail.setVisible(true);
                jfDetail.setLocationRelativeTo(null);
                initTableD();
                HienThiD(or.getDsSanPham());
                txttong.setText(String.valueOf(or.getTongTien()));
                txtmadh.setText(or.getMaDH());
                txtngay.setText(String.valueOf(or.getNgayHT()));
                KhoaChinhSua();
            }  
        }                       
    }//GEN-LAST:event_tbDHMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        Order or = new Order();
        int choose = tbDH.getSelectedRow();//gán dòng muốn xóa vào một biến del kiểu int       
        try {          
            if(choose == -1) {//Khi chưa chọn dòng nào
                JOptionPane.showMessageDialog(this, " Chọn sản đơn hàng cần xóa","Error",JOptionPane.WARNING_MESSAGE);
            }
            else {
                or = ltOr.get(choose);
                int confirm = JOptionPane.showConfirmDialog(this,"Xác nhận xoá","Xác nhận",JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION) {
                    ltOr.remove(choose);
                    db.saveFile(fileor, ltOr);
                    HienThi(ltOr);
                    JOptionPane.showMessageDialog(this, "Xoá thành công!","Information",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            //System.out.println(err.toString());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        ArrayList<Order> ltOrder = new ArrayList<>();
        ArrayList<Order> check = new ArrayList<>();
        Order or = new Order();
        String choose = txtTimKiem.getText();
        if(choose.equals("")){
            JOptionPane.showMessageDialog(this, "Nhập mã tìm kiếm","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            for(Order o : ltOr){
                String ma = removeDiacriticalMarks(o.getMaDH());
                String maIP = removeDiacriticalMarks(choose);
                if(ma.contains(choose)) {
                    ltOrder.add(o);
                }
            }
            HienThi(ltOrder);
            txtTimKiem.setText("");
        }     
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        HienThi(ltOr);
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtSLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLCActionPerformed

    private void tbDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDetailMouseClicked
        // TODO add your handling code here:
        Order or = new Order();
        Product pr = new Product();
        int choose = tbDetail.getSelectedRow();
        if(choose != -1) {
            pr = (link.getDsSanPham()).get(choose);
            txtMa.setText(pr.getMaSP());
            txtTen.setText(pr.getTenSP());
            txtSLC.setText(String.valueOf(pr.getSoLuong()));
            txtGB.setText(String.valueOf(pr.getGiaBan()));
            spslm.setValue(pr.getSoLuongMua());           
        }   
    }//GEN-LAST:event_tbDetailMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        Product us = new Product();
        int choose = tbDetail.getSelectedRow();
        try {
            if(choose == -1) {
                JOptionPane.showMessageDialog(jfDetail, "Chọn sản phẩm muốn sửa !!","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                us = (link.getDsSanPham()).get(choose);
                us.setSoLuongMua((int)spslm.getValue());
                
                //boolean check = false;
                if(us.getSoLuongMua() > 0){
                    us.setTongTien((int)spslm.getValue());   
                    (link.getDsSanPham()).set(choose, us);
                    total = 0;
                    for(Product o : (link.getDsSanPham())){
                        total += o.getTongTien();
                    }                 
                    JOptionPane.showMessageDialog(jfDetail, "Cập nhật sản phẩm thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    txttong.setText(Double.toString(total));
                    link.setTongTien(total);
                    db.saveFile(fileor, ltOr);
                    HienThiD(link.getDsSanPham());
                    HienThi(ltOr);
                    txtMa.setText("");
                    txtTen.setText("");
                    txtSLC.setText("");
                    spslm.setValue(0);
                    txtGB.setText("");
                }  
                else{
                    JOptionPane.showMessageDialog(jfDetail, "Số lượng phải lớn hơn 0!","Thông báo",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(jfDetail, err.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        Product us = new Product();
        int choose = tbDetail.getSelectedRow();//gán dòng muốn xóa vào một biến del kiểu int
        try {         
            if(choose == -1) {//Khi chưa chọn dòng nào
                JOptionPane.showMessageDialog(jfDetail, " Chọn sản phẩm cần xoá","Error",JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                us = (link.getDsSanPham()).get(choose);
                int confirm = JOptionPane.showConfirmDialog(jfDetail,"Xác nhận xoá","Xác nhận",JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION) {
                    (link.getDsSanPham()).remove(choose);
                    total = 0;
                    for(Product o : link.getDsSanPham()){
                        total += o.getTongTien();
                    }  
                    txttong.setText(String.valueOf(total));
                    HienThiD(link.getDsSanPham());                   
                    link.setTongTien(total);
                    HienThi(ltOr);
                    db.saveFile(fileor, ltOr);
                    JOptionPane.showMessageDialog(jfDetail, "Xoá thành công!","Information",JOptionPane.INFORMATION_MESSAGE);                   
                    //fix hiển thị
                    txtMa.setText("");
                    txtTen.setText("");
                    txtSLC.setText("");
                    spslm.setValue(0);
                    txtGB.setText(""); 
                }
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(jfDetail, err.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            //System.out.println(err.toString());
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMa.setText("");
        txtTen.setText("");
        txtSLC.setText("");
        spslm.setValue(0);
        txtGB.setText("");
        tbDetail.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        jfDetail.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbkActionPerformed
        // TODO add your handling code here:
        Menu gd = new Menu();//Khởi tạo một đối tượng đại diện cho cửa sổ menu
        gd.setVisible(true);//Hiển thị giao diện menu
        gd.setLocationRelativeTo(null);//Giao diện menu được hiển thị ở giữa màn hình
        ManageOrder.this.dispose();//Đóng cửa sổ đăng nhập   
    }//GEN-LAST:event_btnbkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new ManageOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbk;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFrame jfDetail;
    private javax.swing.JSpinner spslm;
    private javax.swing.JTable tbDH;
    private javax.swing.JTable tbDetail;
    private javax.swing.JTextField txtGB;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSLC;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtmadh;
    private javax.swing.JTextField txtngay;
    private javax.swing.JTextField txttong;
    // End of variables declaration//GEN-END:variables
}
